### ISSUE TITLE
Add support for Laravel migration

### ISSUE THREAD

**Issue by damms005** [damms005/devdb-vscode#18]
When loaded in a Laravel project, provide a means to:

- [ ] ~run migrations at a click of a button~
- [ ] ~create migration~

**Comment by Eazybright** [comment]
@damms005 i would love to work on this!

**Comment by damms005** [comment]
Sweet! Dig right in and let me know if you have any questions.

You may start with the extension backend code because I am yet to make the frontend Vue code repo public yet.

Cheers! 🥂

**Comment by damms005** [comment]
No longer a priority/good fit
