### ISSUE TITLE
SequelizeConnectionError: getaddrinfo EAI_AGAIN error with Docker

### ISSUE THREAD

**Issue by tyler36** [damms005/devdb-vscode#37]
### Extension Version

1.0.11

### OS and Version

Ubuntu 22.04 via WSL2

### VS Code Version

1.85.1

### Database name and Version

mariadb 10.4

### Steps to reproduce

1. Install DDEV
2. Install Laravel following quickstart guide at https://ddev.readthedocs.io/en/latest/users/quickstart/#laravel
3. Confirm site is available
4. Refresh DevDB panel, message displays

```
Connection error for 'mysql dialect': SequelizeConnectionError: getaddrinfo EAI_AGAIN db
```

### Expected behavior

It can access the database with the settings in the `.env` file.

The DEVDB panel only displays the "SqLite Database File Picker" as an option.  It would be nice if I can manually add the settings either through the UI or configuration.

### Screenshots

![image](https://github.com/damms005/devdb-vscode/assets/7234392/0eac1587-1ba9-4fe7-8241-66320f775fd7)

### Additional context

DDEV is a framework-agnostic server solution similar to Laravel Sails.
It automatically updates the `.env` with settings for container database. These can be used to configure other database-viewer software on the OS.

The software looks great in the video, but without DEVDB correctly reading the settings file, or the ability to manually configure it I'm unable to use.

**Comment by damms005** [comment]
This should be fixed by #69.

Please consider re-opening if not.

**Comment by ivangretsky** [comment]
Good day @damms005 ! Can't reopen this issue, but I am now facing the same issue. When using docker-based [ddev](https://ddev.readthedocs.io/en/stable/), which is pretty common nowadays for laravel, I get the same error:

```
SequelizeHostNotFoundError: getaddrinfo ENOTFOUND db
```

Could you please look into this? I will be glad to help in any way possible.

**Comment by damms005** [comment]
Will definitely look into it. Can you share your dev environment please? (OS, app versions, etc.)

**Comment by ivangretsky** [comment]
I am on windows 10 + WSL2. 
Vs Code  1.98.0 (user setup)
Ddev version 1.24.3

**Comment by damms005** [comment]
Laravel DDEV Zero-config support is now added to the latest release ― MySQL and Postgres. Please upgrade to latest version and let me know your epxerience.

![Image](https://github.com/user-attachments/assets/df6c34a8-ea7e-41ec-84ab-a20028b3e00f)

**Comment by tyler36** [comment]
Thank you for the update.

I tested `2.0.7` and I see the "DDEV - Laravel MySQL" similar to the above but when I click it it does not detect any tables.
Is there something else I need to do?

![Image](https://github.com/user-attachments/assets/188c0d54-1fe6-4ab3-b302-97eb0c6ffd4a)

**Comment by damms005** [comment]
@tyler36 please upgrade to latest v2.0.8 and share the DevDb output channel content.

![Image](https://github.com/user-attachments/assets/24c93216-5ebe-4fc9-81ca-81034449c895)

**Comment by tyler36** [comment]
@damms005  I did not see a `2.0.8` version but tried `2.0.10` (next version after `2.0.7` and latest)
Unfortunately, it no longer shows "DDEV Lavavel MySQL", and only shows the SQLIte.

Here are the log outputs:

```log
[Init] Getting available providers... 
[Init] Checking provider: Laravel Local SQLite (default) 
[Init] Checking provider: SQLite Database File Picker 
[Init] Checking provider: Config File 
[Init] Checking provider: Laravel Mysql (with Sail support) 
[Init] Checking provider: Laravel PostgreSQL 
[Init] Checking provider: DDEV - Laravel MySQL 
[Init] Checking provider: Laravel PostgreSQL (DDEV) 
[Init] Checking provider: Adonis MySQL (Lucid ORM) 
[Adonis PostgreSQL] No Adonis database config file found 
[Init] Checking provider: Adonis PostgreSQL (Lucid ORM) 
[Adonis PostgreSQL] No Adonis database config file found 
[Init] Laravel Local SQLite (default) useable in workspace: no 
[Init] SQLite Database File Picker useable in workspace: yes 
[Init] Laravel Mysql (with Sail support) useable in workspace: no 
[Init] Laravel PostgreSQL useable in workspace: no 
[Init] Adonis MySQL (Lucid ORM) useable in workspace: no 
[Init] Adonis PostgreSQL (Lucid ORM) useable in workspace: no 
[Init] Config File useable in workspace: no 
[Init] DDEV - Laravel MySQL useable in workspace: no 
[Init] Laravel PostgreSQL (DDEV) useable in workspace: no 
[Init] Available providers: SQLite Database File Picker 
```

**Comment by damms005** [comment]
Seems it could not detect any running DDEV instance. I am [now releasing a new patch](https://github.com/damms005/devdb-vscode/actions/runs/13824717669) that adds more debug details. Please upgrade when ready and share your findings.

**Comment by damms005** [comment]
You good? @tyler36

**Comment by tyler36** [comment]
@damms005 

Thank you for following up and the updates.

Just test `2.0.12` and 

1. It shows the DDEV Mysql database option, as expected 
1. Clicking "connect" shows the database  and the default 5 tables after migration.
1. Adding a new user via "User::factory()->create()", and refresh the tables show the new user

However ....

If I restart DDEV, I displays an error.

![Image](https://github.com/user-attachments/assets/d73b8786-5548-4944-9b07-7c5674ad949e)

DDEV dynamically generates a port on startup. The error suggests it's still trying to connect on port 32771.
If I type `ddev status`, it shows the new port to be '61078'.

To get it working again, I need to 

- click 'X' to close the database view,
- click 'REFRESH' on the database picker screen
- click 'connect' on 'DDEV Laravel MySQL'

These steps should probably be included in the documentation or, automated if possible.

**Comment by ivangretsky** [comment]
> Laravel DDEV Zero-config support is now added to the latest release ― MySQL and Postgres. Please upgrade to latest version and let me know your epxerience.
> 
> ![Image](https://github.com/user-attachments/assets/df6c34a8-ea7e-41ec-84ab-a20028b3e00f)

Thanks!

**Comment by damms005** [comment]
I turned the multi-step action described by @tyler36 to a one-step action ― just a button click.

I really wish to make it kinda "autorecconnect" as suggested by @ivangretsky, but couldn't figure a way to quickly implement it without bending the matrix of space and time, so went with a lazier approach haha.

Lemme know what you guys think 🤙

![Image](https://github.com/user-attachments/assets/2e4d7b0d-46e8-49d4-8740-db7ff693b6fc)
