### ISSUE TITLE
cross origin resource policy when using tunnel in viscose

### ISSUE THREAD

**Issue by myneid** [damms005/devdb-vscode#40]
### Extension Version

v1.0.11

### OS and Version

macOS

### VS Code Version

v1.85.2

### Database name and Version

mysql 8

### Steps to reproduce

create a tunnel with `code tunnel` then connect to it with a browser.
you get 
[Error] Unrecognized Content-Security-Policy directive 'require-trusted-types-for'.

[Error] Unrecognized Content-Security-Policy directive 'trusted-types'.

and devdb does not show

### Expected behavior

devdb shows

### Screenshots

x

**Comment by damms005** [comment]
Hello @myneid,
Thanks for opening this issue.
I do not use code tunnel and hence do not have plans to support this at the moment.

Cheers! 🥂
