### ISSUE TITLE
Custom table name is not linked in code

### ISSUE THREAD

**Issue by StudioTakken** [damms005/devdb-vscode#42]
### Extension Version

v1.0.11

### OS and Version

Mac OS 14.2.1

### VS Code Version

1.86.0-insider

### Database name and Version

mysql

### Steps to reproduce

1. open a model (like title.php) that uses a custom tablename: protected $table = 'titelbestand';
2. click on the code lens 'View table'

### Expected behavior

It should open de table 'titelbestand' in devdb.

### Screenshots

<img width="512" alt="Scherm­afbeelding 2024-01-21 om 12 05 32" src="https://github.com/damms005/devdb-vscode/assets/23215718/81f647d6-98cc-4d62-9bba-a6f9ebbc543e">

<img width="573" alt="Scherm­afbeelding 2024-01-21 om 12 06 51" src="https://github.com/damms005/devdb-vscode/assets/23215718/3cad6d2a-6e48-4bf0-a88a-58d18d62a894">

**Comment by StudioTakken** [comment]
I did provide two screenshots...
<img width="573" alt="Scherm­afbeelding 2024-01-21 om 12 06 51" src="https://github.com/damms005/devdb-vscode/assets/23215718/a63a1959-f294-400d-9d1b-9e30893f5d4d">
<img width="512" alt="Scherm­afbeelding 2024-01-21 om 12 05 32" src="https://github.com/damms005/devdb-vscode/assets/23215718/66a7f617-3679-408f-916d-1bb7f3ec6947">

**Comment by damms005** [comment]
Sorry I had a strict rule for the screenshot regex.

Now relaxed. Thanks for your patience!

This should be a quick fix. I should have an update shortly.
