### ISSUE TITLE
I didn't see MySQL to connect  

### ISSUE THREAD

**Issue by ahmadnajmdev** [damms005/devdb-vscode#44]
### Extension Version

v0.1.6

### OS and Version

Windows 11

### VS Code Version

v1.86

### Database name and Version

mysql  8.2.4 installed with xampp

### Steps to reproduce

1. Launch VS Code
2. Open DevDB on Termina;

### Expected behavior

![image](https://github.com/damms005/devdb-vscode/assets/86409804/06a9d823-df15-4a0f-a1ca-45c3020e7ff3)

### Screenshots

![image](https://github.com/damms005/devdb-vscode/assets/86409804/ac8058ce-e8d8-4e50-8718-cff22653167d)

**Comment by damms005** [comment]
Is this a Laravel app and your database server is already started?

**Comment by ahmadnajmdev** [comment]
Hi Damilola,

Yes, I already contacted my Laravel project to MySQL database.

**Comment by damms005** [comment]
Oh shoot!

You're on v0.1.6.

Please update to the latest version and try again.
