### ISSUE TITLE
When sqlite3 file picker clicked, vscode will be closed

### ISSUE THREAD

**Issue by ehsansafari** [damms005/devdb-vscode#49]
### Extension Version

v1.3.1

### OS and Version

Arch 6.7.4-arch1-1

### VS Code Version

v1.86.1

### Database name and Version

Sqlite3

### Steps to reproduce

When clicked, vscode will be closed

### Expected behavior

.

### Screenshots

![photo_2024-02-16_15-21-08](https://github.com/damms005/devdb-vscode/assets/19387708/12a59aaa-9ada-41be-854b-4ff757a14d1a)

**Comment by damms005** [comment]
This is weird because I believe the extension runs in a separate Electron process.

Can you provide a short clear screen recording of this please?

This will help me triage this better.

**Comment by ehsansafari** [comment]
I updated to v1.3.2 Problem solved.

**Comment by damms005** [comment]
Thanks for the update.

Will close this now :+1:
