### ISSUE TITLE
Extension breaks the system Cmd-K (Clear Terminal) shortcut in VSCode

### ISSUE THREAD

**Issue by rivaros** [damms005/devdb-vscode#55]
### Extension Version

1.6.26

### OS and Version

MacOS Ventura 13.5

### VS Code Version

1.87.2

### Database name and Version

n/a

### Steps to reproduce

- Install extension
- Try to type something in Terminal and press Cmd-K (Ctrl-K on Linux/Win)

### Expected behavior

Extension should not prevent useful default system shortcuts

### Screenshots

<img width="2347" alt="Screenshot 2024-03-30 at 11 20 38 AM" src="https://github.com/damms005/devdb-vscode/assets/1242369/3f7f96ef-1fb4-4d4c-9897-697092b2608e">

**Comment by damms005** [comment]
You can [simply remap the keybinding](https://code.visualstudio.com/docs/getstarted/keybindings) for DevDb from the default `Ctrl K D` to any other shortcut hat works for you.
