### ISSUE TITLE
Large scroll bar makes it hard to see Cell content, Schema and other options

### ISSUE THREAD

**Issue by mansoorkhan96** [damms005/devdb-vscode#66]
### Extension Version

1.11.4	

### OS and Version

Macos Sonoma Version 14.5 (23F79)

### VS Code Version

1.92.2

### Database name and Version

Mysql 8

### Steps to reproduce

Large scroll bar makes it hard to see Cell content, Schema, Prettify and other options

1. Open Up devDB tab in bottom panel.
2. Open any DB table.
3. Now scroll the radio options on top right, you will see the scrollbar hides the options completely. Once scroller appears, try to hover on scrollbar too.

### Expected behavior

Scrolling should not hide the options.

### Screenshots

![image](https://github.com/user-attachments/assets/120e6af1-d18a-4250-9f3a-b7932b97ffe2)

**Comment by mansoorkhan96** [comment]
@damms005 I have added screenshot can you please take a look.

**Comment by damms005** [comment]
Please ensure to update to latest version. Latest version screenshot on my macOS below:

![image](https://github.com/user-attachments/assets/d9ddaac3-828c-4d21-afa6-e625c0faeaed)
