### ISSUE TITLE
`.devdbrc` not detected in multi root projects

### ISSUE THREAD

**Issue by bilogic** [damms005/devdb-vscode#68]
### Extension Version

1.13.2

### OS and Version

Ubuntu 22.04

### VS Code Version

1.92.2

### Database name and Version

mysql 8.0.37

### Steps to reproduce

```
[
  {
    "name": "My test MySQL database", // <-- to identify the connection
    "type": "mysql", // <- or "mariadb" if you are using MariaDB
    "host": "...",
    "port": "...",
    "username": "...",
    "password": "...",
    "database": "..." // <-- the database to show in VS Code DevDb view
  }
]
```

```
{
    "folders": [
        {
            "path": "."
        },
    ]
}
```

Partial contents of my `.code-workspace` file. The contents of `.devdbrc` do not appear in the UI.

### Expected behavior

Expected the database connection to show up on the UI

### Screenshots

![image](https://github.com/user-attachments/assets/1932b8ce-010c-4d3a-bd62-248b7f432a87)
Only this appears

### Additional context

It might be more apt to have connections stored in the inheritable model of VSCode user/workspace settings. 

This has many benefits including allow each developer to have their own DB connection/settings rather than have `.devdbrc` commited into git

**Comment by bilogic** [comment]
Pretty sure I had screenshot attached...

**Comment by damms005** [comment]
Had a snag in the regex used to detect screenshots. It is now fixed and hopefully no more false negatives in det4ecting screenshots in issues. Sorry about the stress. 

Yes, about the multi-root projects support, I totally agree with you and will be a good feature. However, I currently don't have a need for it nor can I commit the time to address it right now.

I have attached updated the labels for this issue and added the `feature` label. I'll hopefully get to add this soon enough in the future. PRs also welcomed! 😍

**Comment by bilogic** [comment]
ok thanks!

**Comment by sunilv45** [comment]
**Extension Version**
v1.13.4

**OS and Version**
Windows_NT x64 10.0.19045

**VS Code Version**
Version: 1.93.1

**Database name and Version**
8.0.31 MySQL

**Also configure when not auto detected in root directory of laravel**
```
[
  {
    "name": "My local", // <-- to identify the connection
    "type": "mysql", // <- or "mariadb" if you are using MariaDB
    "host": "localhost", //Also i tried with 127.0.0.1
    "port": "3306",
    "username": "username",
    "password": "mypassword",
    "database": "demo_app" // <-- the database to show in VS Code DevDb view
  }
]
```

The contents of .devdbrc do not appear in the UI.

**Expected behavior to show the UI for mysql with connection**

Nothing was showing only sqlite was visible

Screenshots
![devdb issue](https://github.com/user-attachments/assets/ac132d6a-107c-4ce1-8cf5-8ae08b941006)

Only this appears

**Comment by damms005** [comment]
@sunilv45 please do not cross-post, more so this is a closed issue.

Else, subscribers of this thread will get notified of unrelated issue, which is not cool 😊
