### ISSUE TITLE
Unable to Open "application" Table

### ISSUE THREAD

**Issue by NomadicDaddy** [damms005/devdb-vscode#73]
### Extension Version

v1.14.1

### OS and Version

Windows 11

### VS Code Version

v1.93.1

### Database name and Version

SQLite v3.46.0

### Steps to reproduce

From the table list, all other tables open a tab except 'application'.

### Expected behavior

'application' should open in a tab as usual.

### Screenshots

![image](https://github.com/user-attachments/assets/fec10d1a-3aa1-49ea-9806-18706173a8c8)

**Comment by damms005** [comment]
You need to click on the table name to get it to open.

Please feel-free to re-open with more details if this is not the case.

**Comment by NomadicDaddy** [comment]
Yes. I can clock it as many times as I want, but that table does not open.
All others do.

Sent.

**Comment by damms005** [comment]
I am unable to reproduce this on my macOS and do not have a Windows OS handy to repro it.

Can you open VS Code devtools, repro the issue, and then screenshot the devtools content here?
