### ISSUE TITLE
Filter doesn't work for columns  UUID and INT with postgresql database

### ISSUE THREAD

**Issue by ariel-avila** [damms005/devdb-vscode#75]
### Extension Version

v1.14.6

### OS and Version

macOS 15

### VS Code Version

1.94.0

### Database name and Version

postgresql 17

### Steps to reproduce

1 - Install extension
2 - create .devdbrc file in project root directory
3 - addconfig for postgresql: [
{
"name":"..." ,
"type": "postgres",
"host": "...",
"port": "...",
"username":"...",
"password":"..." ,
"database": "..."
}
]
4 - in DevDB UI try to filter any column UUID or INT

### Expected behavior

I expect to get rows filtered

### Screenshots

![Screenshot 2024-10-05 at 8 59 07 PM](https://github.com/user-attachments/assets/a8dcafde-03e3-4804-8406-06313d015b5c)

**Comment by damms005** [comment]
A fix for this is now released. Please upgrade to version >= v1.14.8

Thanks for reporting 👍 

PS: Nice seeing this in a java project!
