### ISSUE TITLE
the same table could be opened more than one time

### ISSUE THREAD

**Issue by successbyte** [damms005/devdb-vscode#83]
### Extension Version

v1.15.2

### OS and Version

windows 10

### VS Code Version

v1.96.2

### Database name and Version

not related

### Steps to reproduce

click on same table in left sidebar
it opens as much tabs as you want

### Expected behavior

to not open the same table twice or more

### Screenshots

![image](https://github.com/user-attachments/assets/2550692d-7f2a-4bc8-93ba-cc61f1635fd1)

**Comment by damms005** [comment]
Nah this is an expected behaviour.

An example use case is when you need to open mulitple tabs of the same table but apply different filters for each.

**Comment by successbyte** [comment]
Ops didn't think about that 
thanks anyway
